// <auto-generated />
using System;
using CVScore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVScore.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CVScore.Domain.Entities.CvDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParsedData")
                        .HasColumnType("longtext");

                    b.Property<string>("RawText")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CvDocuments");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailedAnalysis")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Improvements")
                        .HasColumnType("longtext");

                    b.Property<Guid>("InterviewAnswerId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Strengths")
                        .HasColumnType("longtext");

                    b.Property<string>("SuggestedAnswer")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewAnswerId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("InterviewQuestionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId");

                    b.ToTable("InterviewAnswers");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CvDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FocusAreas")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TechStack")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CvDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("InterviewProfiles");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AiRationale")
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedAnswerPoints")
                        .HasColumnType("longtext");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("InterviewProfileId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewProfileId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.CvDocument", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.User", "User")
                        .WithMany("CvDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.InterviewAnswer", "InterviewAnswer")
                        .WithOne("Feedback")
                        .HasForeignKey("CVScore.Domain.Entities.Feedback", "InterviewAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewAnswer");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewAnswer", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.InterviewQuestion", "InterviewQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("InterviewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewQuestion");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewProfile", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.CvDocument", "CvDocument")
                        .WithMany("InterviewProfiles")
                        .HasForeignKey("CvDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CVScore.Domain.Entities.User", "User")
                        .WithMany("InterviewProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewQuestion", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.InterviewSession", "InterviewSession")
                        .WithMany("Questions")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewSession", b =>
                {
                    b.HasOne("CVScore.Domain.Entities.InterviewProfile", "InterviewProfile")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("InterviewProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewProfile");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.CvDocument", b =>
                {
                    b.Navigation("InterviewProfiles");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewAnswer", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewProfile", b =>
                {
                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.InterviewSession", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CVScore.Domain.Entities.User", b =>
                {
                    b.Navigation("CvDocuments");

                    b.Navigation("InterviewProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
